Using custom data configuration default
Reusing dataset liar (/home/lily/lyf6/.cache/huggingface/datasets/liar/default/1.0.0/479463e757b7991eed50ffa7504d7788d6218631a484442e2098dabbf3b44514)
100% 3/3 [00:00<00:00, 645.64it/s]
Loading cached processed dataset at /home/lily/lyf6/.cache/huggingface/datasets/liar/default/1.0.0/479463e757b7991eed50ffa7504d7788d6218631a484442e2098dabbf3b44514/cache-d35a42478ef969d3.arrow
Loading cached processed dataset at /home/lily/lyf6/.cache/huggingface/datasets/liar/default/1.0.0/479463e757b7991eed50ffa7504d7788d6218631a484442e2098dabbf3b44514/cache-e33c87c88de34055.arrow
Loading cached processed dataset at /home/lily/lyf6/.cache/huggingface/datasets/liar/default/1.0.0/479463e757b7991eed50ffa7504d7788d6218631a484442e2098dabbf3b44514/cache-94c5609605216dbd.arrow
Loading cached processed dataset at /home/lily/lyf6/.cache/huggingface/datasets/liar/default/1.0.0/479463e757b7991eed50ffa7504d7788d6218631a484442e2098dabbf3b44514/cache-efc3527b9d99d358.arrow
Loading cached processed dataset at /home/lily/lyf6/.cache/huggingface/datasets/liar/default/1.0.0/479463e757b7991eed50ffa7504d7788d6218631a484442e2098dabbf3b44514/cache-a374eb497cc3826f.arrow
Loading cached processed dataset at /home/lily/lyf6/.cache/huggingface/datasets/liar/default/1.0.0/479463e757b7991eed50ffa7504d7788d6218631a484442e2098dabbf3b44514/cache-1dc03a2c7259500f.arrow
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Epoch 0
Training
  0% 0/642 [00:00<?, ?it/s]/home/lily/lyf6/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '






















































































































































































































































































































































































































































































































100% 641/642 [16:50<00:01,  1.56s/it]
100% 642/642 [16:51<00:00,  1.58s/it]






















100% 81/81 [00:47<00:00,  1.70it/s]
























100% 81/81 [00:47<00:00,  1.70it/s]
Current lr: 1e-05
Epoch 1
Training






















































































































































































































































































































































































































































































































100% 642/642 [16:48<00:00,  1.57s/it]
  1% 1/81 [00:00<00:45,  1.74it/s]























100% 81/81 [00:47<00:00,  1.69it/s]























 98% 79/81 [00:46<00:01,  1.68it/s]
Current lr: 1e-05
Epoch 2
100% 81/81 [00:47<00:00,  1.70it/s]






















































































































































































































































































































































































































































































































100% 642/642 [16:47<00:00,  1.57s/it]
  2% 2/81 [00:01<00:46,  1.71it/s]























100% 81/81 [00:47<00:00,  1.70it/s]






















100% 81/81 [00:47<00:00,  1.70it/s]
Traceback (most recent call last):
  File "/data/lily/lyf6/DRO/dhs_modeling.py", line 394, in <module>
    pickle.dump(loss_dict, open('loss_liar.pkl', 'wb'))
AttributeError: Can't pickle local object 'LossComputer.__init__.<locals>.<lambda>'
Current lr: 1e-05